### ISSUE TITLE
Conversation is not working  bi-directionally

### ISSUE THREAD

**Issue by Tarunjain19** [tamdilip/whatsapp-amazonconnect-chat#2]
Hi Team,
I have implemented the setup as suggested in this article and able to connect with chat agent from my WhatsApp number .

But conversation is not working  bi-directionally  i.e. I have only send message from my number to Agent but not able to 
received the message whatever send by chat agent.

Could you suggest me how to check this issue . It can be any specific country wise number is required for testing.

Thanks & Regards
Tarun Jain

**Comment by tamdilip** [comment]
Hi @Tarunjain19 
I verified once again from my side, the messages are being transferred both ways without any issues.

- Check your NodeJs server logs, if there are any issues in posting the messages back to Twilio's WhatsApp Endpoint.
- Also check the [Twilio Debugger](https://www.twilio.com/console/debugger?quickDate=24) section.
- Make sure all the necessary/valid environment variables needed in [config.js](https://github.com/tamdilip/whatsapp-amazonconnect-chat/blob/master/config/env.js) is updated.

**Comment by Tarunjain19** [comment]
> Hi @Tarunjain19
> I verified once again from my side, the messages are being transferred both ways without any issues.
> 
> * Check your NodeJs server logs, if there are any issues in posting the messages back to Twilio's WhatsApp Endpoint.
> * Also check the [Twilio Debugger](https://www.twilio.com/console/debugger?quickDate=24) section.
> * Make sure all the necessary/valid environment variables needed in [config.js](https://github.com/tamdilip/whatsapp-amazonconnect-chat/blob/master/config/env.js) is updated.

HI 

> Hi @Tarunjain19
> I verified once again from my side, the messages are being transferred both ways without any issues.
> 
> * Check your NodeJs server logs, if there are any issues in posting the messages back to Twilio's WhatsApp Endpoint.
> * Also check the [Twilio Debugger](https://www.twilio.com/console/debugger?quickDate=24) section.
> * Make sure all the necessary/valid environment variables needed in [config.js](https://github.com/tamdilip/whatsapp-amazonconnect-chat/blob/master/config/env.js) is updated.

Hi Dilipan,

Thank you very much for your response .I have put some logs in code for troubleshooting :

Code : Twilio-client.js

const ENV = require("../config/env");
const { TwilioClient } = require("../config/config");

let sendMessage = (content, customerNumber) => {
   console.log("content sent by agent::", content);
   console.log("customerNumber in Twilio::", customerNumber);
   console.log("ENV.TWILIO_WHATSAPP_NUM::", ENV.TWILIO_WHATSAPP_NUM);
  TwilioClient.messages
    .create({
      from: ENV.TWILIO_WHATSAPP_NUM,
      body: content,
      to: customerNumber
    })
    .then(message => console.log("Success::sendMessage", message.sid));
    console.log(" After sendMessage");
};
console.log("sendMessage::", sendMessage);
module.exports = { sendMessage };


Output:

content sent by agen:: hello
customerNumber in Twilio:: whatsapp:+9180000000
ENV.TWILIO_WHATSAPP_NUM:: +1400000000
 After sendMessage

Note: not printed this line in logs  " console.log("Success::sendMessage", message.sid));

I am not sure this line should be printed or not . If it should be printed then issue may be due to this.

Need your support to crack this issue.

Thanks & Regards
Tarun Jain

**Comment by tamdilip** [comment]
- Add a "catch" block to the "create" call and check on the error logs for detailed info.

- Also try to send a programmatic Twilio SMS with a standalone [node js sample](https://www.twilio.com/docs/sms/send-messages?code-sample=code-send-an-sms-message&code-language=Node.js&code-sdk-version=3.x)

**Comment by Tarunjain19** [comment]
> * Add a "catch" block to the "create" call and check on the error logs for detailed info.
> * Also try to send a programmatic Twilio SMS with a standalone [node js sample](https://www.twilio.com/docs/sms/send-messages?code-sample=code-send-an-sms-message&code-language=Node.js&code-sdk-version=3.x)
Hi Dilipan,

Thank you for your suggestion and now issue is resolve .

Problem was Twilio number configuration, It  should be configure like whatsapp:+140000000  but I was configured +140000000.

 I found one more issue during testing, once agent disconnect the call and customer initiate the call again then application generate the Access denied error in nodes logs.

Websocket::Client connection closed
Error::sendMessageToChat AccessDeniedException: Access denied

Any idea how to resolve this issue.

Thanks & Regards
Tarun Jain

**Comment by Tarunjain19** [comment]
Now issue resolve thanks for your support
